### ISSUE TITLE
Help with ESP32 devkit v1

### ISSUE THREAD

**Issue by Lippo89** [maskaz/Esphome_custom_dust_sensor#1]
Hi, is this possible to get work with the ESP32 devkit v1? What I have to modify, I would like to use GPIO13 for led and GPIO32 for read?

**Comment by maskaz** [comment]
Hi, i think it might easily work because ESPHOME support ESP32 board.
First follow ESPHome Configure manual and configure new device choosing ESP32 platform.
In the file sharp_sensor.h you should change pin config:
From:
   pinMode(D6, OUTPUT);     // sensor led pin         
   pinMode(A0, INPUT);      // output form sensor

To:

   pinMode(13, OUTPUT);     // sensor led pin         
   pinMode(32, INPUT);      // output form sensor

Good luck.

**Comment by Lippo89** [comment]
Hello, it's working now. I was using GPIO13 and GPIO32 in sharp_sensor.h and because of that I got compiling errors. Thanks for the help and making this custom sensor!

**Comment by rspierz** [comment]
I am trying to set this up with a ESP-WROOM-32 with the same pins listed here. My esphome log returns zeros ("[sensor:092]: 'Dust sensor': Sending state 0.00000 % with 2 decimals of accuracy"). Im not sure if its the config of esphome or I have a defective unit but i am getting 5v at the sensor.

**Comment by maskaz** [comment]
Hi, 5v it is too much.
ESP only can handle 3v3 input. It is possible that you burned ESP input.

Please follow internet how to's to connect sensor with ESP.
Example attached:

Regards

czw., 31 gru 2020, 20:01 użytkownik rspierz <notifications@github.com>
napisał:

**Comment by maskaz** [comment]
Sorry i forgot add link:

http://www.esp8266learning.com/wemos-dust-sensor-example.php

czw., 31 gru 2020, 20:01 użytkownik rspierz <notifications@github.com>
napisał:

**Comment by rspierz** [comment]
Ok setting it to the 3v input on esp returns the same results. Im not really sure how i can troubleshoot into the sensor more.
